'use client';
import { useEffect,useRef,useState } from 'react';
import Image from 'next/image';
import { ArrowLeft,ArrowRight,ArrowUpRight,Check } from 'lucide-react';
import Modal from './modal';
const spaces=[
 {id:'room',number:'01',title:'Habiter sereinement',category:'VOTRE ESPACE À VOUS',image:'/images/experience-room.webp',description:'Un lieu pour se reposer, se concentrer et se sentir chez soi.',intro:'L’intimité d’un espace personnel, la richesse d’une vie de campus.',body:'Le projet prévoit des logements meublés pensés pour le quotidien étudiant. L’aménagement recherche un équilibre entre repos, travail et rangements, dans une atmosphère simple et chaleureuse.',features:['Logements meublés envisagés','Un espace dédié au travail personnel','Des matériaux et teintes naturels','Une conception attentive au confort d’usage']},
 {id:'study',number:'02',title:'Apprendre ensemble',category:'LES IDÉES SE RENCONTRENT',image:'/images/experience-study.webp',description:'Des espaces communs pour apprendre, échanger et avancer ensemble.',intro:'Quand le lieu de vie devient aussi un lieu d’émulation.',body:'Des espaces de coworking et d’étude sont intégrés à la vision du campus. Ils ont vocation à favoriser le travail individuel, les projets de groupe et les rencontres entre étudiants.',features:['Espaces de coworking prévus','Tables de travail partagées','Lieux propices aux échanges','Une continuité entre habitat et apprentissage']},
 {id:'garden',number:'03',title:'Vivre pleinement',category:'UNE VIE AU-DELÀ DES COURS',image:'/images/experience-garden.webp',description:'Des moments de détente, des rencontres et une place pour la nature.',intro:'Un campus se reconnaît aussi à la vie entre ses bâtiments.',body:'Le projet associe les logements à des espaces de restauration, de sport et de détente. Les espaces extérieurs participent à la vie collective et à l’équilibre du quotidien étudiant.',features:['Espaces de détente envisagés','Restauration et sport dans le programme','Lieux partagés et rencontres','Une attention portée au paysage']},
];
export default function CampusExperience(){
 const rail=useRef<HTMLDivElement>(null);const [selected,setSelected]=useState<(typeof spaces)[number]|null>(null);const [position,setPosition]=useState(0);
 useEffect(()=>{const element=rail.current;if(!element)return;const update=()=>setPosition(element.scrollWidth>element.clientWidth?element.scrollLeft/(element.scrollWidth-element.clientWidth):1);const observer=new ResizeObserver(update);observer.observe(element);update();return()=>observer.disconnect();},[]);
 const move=(direction:number)=>{const el=rail.current;if(el)el.scrollBy({left:direction*(el.querySelector('article')?.clientWidth||el.clientWidth)*1.04,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
 return <section className="campus-experience" id="experience"><div className="experience-shell"><div className="section-kicker"><span>04 / L’EXPÉRIENCE CAMPUS</span><span>BIEN PLUS QU’UN LOGEMENT</span></div><div className="experience-heading"><div><h2>Un quotidien <em>qui fait grandir.</em></h2><p>Habiter, apprendre et se retrouver : trois dimensions d’un même campus.</p></div><div className="rail-controls"><button onClick={()=>move(-1)} disabled={position<.01} aria-label="Voir l’espace précédent"><ArrowLeft size={19}/></button><button onClick={()=>move(1)} disabled={position>.99} aria-label="Voir l’espace suivant"><ArrowRight size={19}/></button></div></div><div ref={rail} className="experience-rail" role="region" aria-label="Espaces du campus, galerie défilante" tabIndex={0} onScroll={event=>{const el=event.currentTarget;setPosition(el.scrollWidth>el.clientWidth?el.scrollLeft/(el.scrollWidth-el.clientWidth):1);}}>{spaces.map(space=><article className="experience-card" key={space.id}><button type="button" className="experience-open" onClick={()=>setSelected(space)} aria-label={`Découvrir : ${space.title}`}><div className="experience-image"><Image src={space.image} alt={space.title==='Habiter sereinement'?'Vision d’un logement étudiant meublé, bureau et lumière naturelle':space.title==='Apprendre ensemble'?'Vision d’un espace de coworking avec des étudiants':'Vision d’un jardin de campus avec des étudiants'} fill sizes="(max-width: 700px) 88vw, 50vw"/><span>{space.category}</span><i><ArrowUpRight size={23}/></i><div className="experience-image-wash"/></div><div className="experience-card-title"><span>{space.number}</span><h3>{space.title}</h3><span className="discover-label">Découvrir</span></div><p>{space.description}</p></button></article>)}</div><div className="experience-bottom"><p>Glissez, utilisez les flèches ou la barre pour explorer.</p><span>Visuels d’intention · aménagements non définitifs</span></div></div>{selected&&<Modal title={selected.title} onClose={()=>setSelected(null)} wide><div className="experience-modal-image"><Image src={selected.image} alt={selected.title} fill sizes="90vw"/></div><div className="experience-modal-copy"><p className="eyebrow terracotta">{selected.category}</p><h2>{selected.title}</h2><p className="large-copy">{selected.intro}</p><p>{selected.body}</p><ul className="feature-list">{selected.features.map(feature=><li key={feature}><Check size={17}/>{feature}</li>)}</ul><p className="concept-notice">Maquette exploratoire pour l’élaboration du projet. Les visuels, aménagements et prestations présentés ne constituent pas une offre officielle ou définitive.</p><a className="button" href="#contact" onClick={()=>setSelected(null)}>Parlons du campus <ArrowUpRight size={18}/></a></div></Modal>}</section>;
}
