'use client';
import { useRef, useState } from 'react';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import { ArrowUpRight, ArrowDown, Menu, X, Leaf, Sun, Wind, GraduationCap, MapPin, Plus, Minus } from 'lucide-react';
import Campus from './campus';
gsap.registerPlugin(ScrollTrigger, useGSAP);
const stages = [ ['Terre locale','Une ressource d’ici. Une ambition pour demain.','La terre est le point de départ d’une construction qui valorise les ressources locales.'], ['Brique BTC','La terre prend une nouvelle forme.','Les briques de terre crue stabilisée placent le matériau local au cœur du projet.'], ['Murs durables','Bâtir avec intelligence.','Des murs en BTC et une conception bioclimatique pour des lieux adaptés à leur environnement.'], ['Bâtiments','Une architecture pensée pour apprendre.','Les volumes se dessinent autour des espaces de vie, de rencontre et de travail.'], ['Campus','Un lieu de vie. Un avenir à construire.','Environ 310 logements meublés prévus à Man, avec coworking, restauration, sport et détente.'] ];
const spaces = [{ number:'01', title:'Habiter sereinement',type:'Logements meublés',text:'Des espaces personnels pensés pour le quotidien et la réussite étudiante.',className:'room'},{number:'02',title:'Apprendre ensemble',type:'Coworking & étude',text:'Des lieux partagés pour travailler, échanger et faire grandir les idées.',className:'study'},{number:'03',title:'Vivre pleinement',type:'Sport & détente',text:'Un campus qui fait une place au lien social et à l’équilibre de vie.',className:'garden'}];
export default function Home() {
const root = useRef<HTMLDivElement>(null); const [menu,setMenu]=useState(false);const [stage,setStage]=useState(0);const [faq,setFaq]=useState<number|null>(0);const [contact,setContact]=useState('');
useGSAP(()=>{
 const mm=gsap.matchMedia(); let lenis:Lenis|undefined; let tick:((time:number)=>void)|undefined;
 mm.add('(prefers-reduced-motion: no-preference)',()=>{
 lenis=new Lenis({duration:1.1,anchors:true}); lenis.on('scroll',ScrollTrigger.update);tick=time=>lenis?.raf(time*1000);gsap.ticker.add(tick);
 gsap.from('.hero-line > span',{yPercent:110,opacity:0,duration:1.3,stagger:.15,ease:'power3.out'});gsap.from('.hero-detail',{opacity:0,y:24,delay:.7,duration:1});
 gsap.to('.hero-campus',{y:85,scale:1.08,scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
 gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:45,opacity:0,duration:.85,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));
 const tl=gsap.timeline({scrollTrigger:{trigger:'.build-section',start:'top top',end:()=>`+=${window.innerHeight*4}`,pin:'.build-pin',scrub:.7,invalidateOnRefresh:true,onUpdate:self=>setStage(Math.min(4,Math.floor(self.progress*5)))}});
 gsap.set('.build-scene .single-brick',{opacity:0,y:-100});gsap.set('.build-scene .building',{opacity:0,y:-100});gsap.set('.build-scene .landscape',{opacity:0,y:25});gsap.set('.build-scene .ground',{opacity:.3});
 tl.to('.build-progress',{scaleX:1,ease:'none',duration:5},0).to('.build-scene .earth',{opacity:0,scale:.7,transformOrigin:'50% 70%',duration:.5},.7).to('.build-scene .single-brick',{opacity:1,y:0,duration:.6},.8).to('.build-scene .single-brick',{opacity:0,scale:.7,duration:.4},1.8).fromTo('.build-scene .front',{opacity:1,clipPath:'inset(85% 0% 0% 0%)',y:0},{opacity:1,clipPath:'inset(0% 0% 0% 0%)',duration:1.5,immediateRender:false},1.9).to('.build-scene .rear',{opacity:1,y:0,duration:1},3).to('.build-scene .ground',{opacity:1,duration:.8},3.5).to('.build-scene .landscape',{opacity:1,y:0,duration:.8},4).to('.build-scene .campus-art',{scale:1.03,duration:1},4);
 const track=root.current?.querySelector<HTMLElement>('.space-track'); if(track) gsap.to(track,{x:()=>-Math.max(0,track.scrollWidth-track.parentElement!.clientWidth),ease:'none',scrollTrigger:{trigger:'.life-section',start:'top top',end:()=>`+=${Math.max(500,track.scrollWidth-track.parentElement!.clientWidth)}`,pin:'.life-pin',scrub:1,invalidateOnRefresh:true}});
 return ()=>{if(tick)gsap.ticker.remove(tick);lenis?.destroy();};
 });
 mm.add('(prefers-reduced-motion: reduce)',()=>{setStage(4);});
 return ()=>mm.revert();
},{scope:root});
const close=()=>setMenu(false);
return <div ref={root}>
<a href="#main" className="skip-link">Aller au contenu</a>
<header className="header"><a href="#" className="wordmark" aria-label="GreenBuild, accueil"><span className="brand-icon"><Leaf size={20}/></span>GREEN<span>BUILD</span></a><nav id="mobile-nav" className={menu?'nav open':'nav'} aria-label="Navigation principale"><a href="#vision" onClick={close}>Notre vision</a><a href="#campus" onClick={close}>Le campus</a><a href="#innovation" onClick={close}>Innovation BTC</a><a href="#investir" onClick={close}>Investir <ArrowUpRight size={15}/></a><a className="nav-contact" href="#contact" onClick={close}>Parlons de demain <ArrowUpRight size={16}/></a></nav><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'Fermer le menu':'Ouvrir le menu'} aria-expanded={menu} aria-controls="mobile-nav">{menu?<X/>:<Menu/>}</button></header>
<main id="main"><section className="hero"><div className="hero-grid" aria-hidden="true"/><div className="hero-horizon"/><div className="hero-copy"><p className="eyebrow hero-detail"><span className="status-dot"/> L’AVENIR PREND RACINE ICI</p><h1><span className="hero-line"><span>Bâtir durablement,</span></span><span className="hero-line"><span>loger <em>dignement.</em></span></span></h1><p className="hero-description hero-detail">Une nouvelle génération de campus étudiants.<br/>Ancrée en Côte d’Ivoire. Tournée vers l’avenir.</p><a href="#campus" className="button hero-detail">Découvrez le projet <ArrowUpRight size={18}/></a></div><div className="hero-campus"><Campus/></div><div className="hero-bottom hero-detail"><a href="#construction"><span className="scroll-orbit"><ArrowDown size={17}/></span> SCROLL POUR EXPLORER</a><p>TERRE LOCALE.<br/><strong>AMBITION AFRICAINE.</strong></p><span className="hero-location"><MapPin size={15}/> MAN, CÔTE D’IVOIRE</span></div><div className="art-caption">Illustration conceptuelle · architecture non contractuelle</div></section>
<section id="vision" className="vision section"><div className="section-kicker reveal"><span>01 / NOTRE CONVICTION</span><span>UN PROJET À IMPACT</span></div><div className="vision-grid"><h2 className="reveal">L’avenir de l’Afrique<br/>se construit aussi<br/>dans <em>ses campus.</em></h2><div className="vision-copy reveal"><p className="large-copy">Un logement digne ouvre la voie à de grandes ambitions.</p><p>GreenBuild développe des résidences universitaires écologiques pour répondre à deux enjeux essentiels : le logement étudiant et la transition écologique du bâtiment.</p><p>Des matériaux locaux, une architecture bioclimatique et des espaces de vie partagés. Une autre manière de bâtir, au service de l’éducation.</p><a href="#construction" className="text-link">De la terre au campus <ArrowDown size={17}/></a></div></div><div className="values reveal"><span><Leaf/> Construction durable</span><span><GraduationCap/> Inclusion & éducation</span><span><Sun/> Modernité africaine</span></div></section>
<section id="construction" className="build-section"><div className="build-pin"><div className="build-top"><span className="eyebrow">02 / DE LA TERRE À L’AVENIR</span><span className="build-counter">0{stage+1} <span>/ 05</span></span></div><div className="build-layout"><div className="build-copy"><p className="eyebrow terracotta">{stages[stage][0]}</p><h2 key={stage}>{stages[stage][1]}</h2><p>{stages[stage][2]}</p><span className="build-hint">Faites défiler pour construire <ArrowDown size={15}/></span></div><div className="build-scene"><div className="scene-grid" aria-hidden="true"/><Campus construction/><span className="scene-label">GREENBUILD / ÉTUDE CONCEPTUELLE</span></div></div><ol className="build-stages">{stages.map(([name],i)=><li key={name} className={stage===i?'active':stage>i?'complete':''}><span>0{i+1}</span>{name}</li>)}</ol><div className="build-progress"/></div></section>
<section id="campus" className="campus section"><div className="section-kicker reveal"><span>03 / LE PROJET PILOTE</span><span><MapPin size={14}/> MAN, CÔTE D’IVOIRE</span></div><div className="campus-heading reveal"><h2>Un campus pour vivre.<br/><em>Un tremplin pour demain.</em></h2><p>À proximité d’un pôle universitaire, le projet pilote de Man réunit habitat, apprentissage et vie collective dans un même lieu.</p></div><div className="campus-panel reveal"><div className="campus-picture"><Campus/><span className="picture-tag">LE CAMPUS GREENBUILD · VISION DU PROJET</span></div><div className="campus-stats"><span className="eyebrow">PENSÉ POUR LA VIE ÉTUDIANTE</span><p className="big-number">≈ 310</p><p>logements meublés prévus</p><div className="stat-line"><span>Matériau central</span><strong>Briques BTC</strong></div><div className="stat-line"><span>Conception</span><strong>Bioclimatique</strong></div><div className="stat-line"><span>Implantation pilote</span><strong>Man</strong></div><a href="#contact" className="text-link">Recevoir les informations du projet <ArrowUpRight size={18}/></a><small>Projet en développement. Les caractéristiques définitives seront précisées à mesure de son avancement.</small></div></div></section>
<section className="life-section"><div className="life-pin section"><div className="section-kicker"><span>04 / L’EXPÉRIENCE CAMPUS</span><span>BIEN PLUS QU’UN LOGEMENT</span></div><h2>Un quotidien <em>qui fait grandir.</em></h2><div className="space-window"><div className="space-track">{spaces.map(space=><article className="space-card" key={space.number}><div className={`interior ${space.className}`} aria-hidden="true"><div className="interior-window"/><div className="interior-furniture"/><div className="interior-plant"/><span>{space.type}</span></div><div className="space-title"><span>{space.number}</span><h3>{space.title}</h3><ArrowUpRight/></div><p>{space.text}</p></article>)}</div></div><p className="life-note">Illustrations d’ambiance · espaces envisagés pour le projet pilote</p></div></section>
<section id="innovation" className="innovation section"><div className="section-kicker reveal"><span>05 / INNOVATION BTC</span><span>LA TERRE, RÉINVENTÉE</span></div><div className="innovation-grid"><div className="brick-wall reveal" aria-label="Illustration d’un mur en briques de terre stabilisée">{Array.from({length:24},(_,i)=><div className="btc-brick" key={i}/>)}<span>MATIÈRE LOCALE.<br/>VISION CONTEMPORAINE.</span></div><div className="reveal"><p className="eyebrow terracotta">BRIQUES DE TERRE CRUE STABILISÉE</p><h2>L’innovation a<br/>déjà <em>ses racines.</em></h2><p>Les BTC valorisent la terre comme matériau de construction. GreenBuild les associe à une architecture contemporaine, pensée pour le climat et les usages du campus.</p><div className="innovation-item"><Leaf/><div><h3>Valoriser les ressources locales</h3><p>Faire du territoire un point de départ de la construction.</p></div></div><div className="innovation-item"><Wind/><div><h3>Concevoir avec le climat</h3><p>Intégrer la ventilation et le confort dans la réflexion architecturale.</p></div></div><div className="innovation-item"><Sun/><div><h3>Construire une vision durable</h3><p>Relier choix des matériaux, qualité d’usage et impact social.</p></div></div></div></div></section>
<section className="impact section"><div className="section-kicker reveal"><span>06 / UNE AMBITION AFRICAINE</span><span>ANCRAGE LOCAL, HORIZON CONTINENTAL</span></div><div className="impact-grid"><div className="reveal"><h2>Commencer à Man.<br/><em>Voir plus loin.</em></h2><p>Notre ambition : devenir une référence africaine du logement étudiant durable et accessible. Le pilote ivoirien constitue la première étape de cette vision.</p><div className="impact-chips"><span>Éducation</span><span>Habitat digne</span><span>Économie locale</span></div></div><div className="africa-map reveal"><svg viewBox="0 0 430 400" role="img" aria-label="Carte schématique de l’Afrique : projet pilote à Man en Côte d’Ivoire"><path d="M100 37L178 22 241 47 255 76 285 99 304 141 356 148 326 184 296 204 286 252 264 278 253 333 218 372 196 350 180 307 166 274 144 254 145 223 117 196 81 190 53 161 58 113 78 96 78 66Z" fill="#d0d8bf"/><path d="M309 286L330 266 335 300 322 337 308 331Z" fill="#d0d8bf"/><path d="M80 150L285 150M96 182L300 182M144 215L290 215M156 247L280 247M170 279L265 279M183 311L253 311" stroke="#faf8f2" strokeOpacity=".65"/><circle cx="108" cy="182" r="20" fill="#c0623a" opacity=".15"/><circle cx="108" cy="182" r="5" fill="#c0623a"/><path d="M108 182L40 231" stroke="#c0623a"/><text x="15" y="250" fill="#14532d" fontSize="14" fontWeight="bold">MAN</text><text x="15" y="267" fill="#566353" fontSize="10">CÔTE D’IVOIRE</text></svg><p>Une ambition de déploiement en Afrique de l’Ouest.</p></div></div></section>
<section id="investir" className="invest section"><div className="invest-orbit" aria-hidden="true"/><p className="eyebrow reveal">07 / CONSTRUISONS LA SUITE ENSEMBLE</p><h2 className="reveal">Investir dans un campus.<br/><em>Croire en une génération.</em></h2><p className="reveal">Investisseurs, institutions, banques, collectivités et partenaires : prenons part à une nouvelle vision du logement étudiant en Afrique.</p><a href="#contact" onClick={()=>setContact('investisseur')} className="button light reveal">Devenir partenaire <ArrowUpRight size={18}/></a><div className="invest-bottom reveal"><span>IMPACT SOCIAL</span><span>CONSTRUCTION DURABLE</span><span>VISION À LONG TERME</span></div></section>
<section className="faq section"><div className="faq-grid"><div className="reveal"><p className="eyebrow">LES QUESTIONS ESSENTIELLES</p><h2>Comprendre<br/><em>le projet.</em></h2></div><div className="reveal">{[['À qui s’adressent les résidences GreenBuild ?','Le projet est pensé pour les étudiants et leurs familles, avec l’ambition de proposer un logement digne et un environnement favorable à la réussite académique.'],['Où se situe le projet pilote ?','Le projet pilote est prévu à Man, en Côte d’Ivoire, à proximité immédiate d’un pôle universitaire. Les informations sur le site définitif seront communiquées au fil du développement.'],['Le campus est-il déjà ouvert ?','Le campus est un projet en développement. Les dates d’ouverture, tarifs et modalités de réservation seront communiqués lorsqu’ils seront confirmés.'],['Comment participer au projet ?','Utilisez le formulaire ci-dessous pour préparer votre demande en tant qu’investisseur, partenaire institutionnel, étudiant ou famille.']].map(([q,a],i)=><div className="faq-item" key={q}><h3><button aria-expanded={faq===i} aria-controls={`answer-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={18}/>:<Plus size={18}/>}</button></h3><div id={`answer-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></div></section>
<section id="contact" className="contact section"><div className="section-kicker reveal"><span>08 / PRENONS CONTACT</span><span>L’AVENIR COMMENCE PAR UN ÉCHANGE</span></div><div className="contact-grid"><div className="reveal"><h2>Votre prochaine idée<br/>peut <em>tout construire.</em></h2><p>Présentez-nous votre intérêt pour GreenBuild.</p><img src="/images/greenbuild-logo.jpg" width="300" height="212" alt="GreenBuild — Bâtir durablement, loger dignement." className="contact-logo"/></div><ContactForm interest={contact}/></div></section>
</main><footer className="footer"><div className="footer-top"><a className="wordmark" href="#">GREEN<span>BUILD</span></a><p>Bâtir durablement, loger dignement.</p><a href="#main" className="back-top">Retour en haut <ArrowUpRight size={16}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} GreenBuild SAS</span><span>Man · Côte d’Ivoire · Afrique</span><span>Le futur a ses racines.</span></div></footer></div>;
}
function ContactForm({interest}:{interest:string}) {
const [prepared,setPrepared]=useState('');
return <form className="contact-form reveal" key={interest} onSubmit={event=>{event.preventDefault();const d=new FormData(event.currentTarget);setPrepared(`Bonjour GreenBuild,\n\nJe suis ${d.get('name')} (${d.get('interest')}).\nMon adresse e-mail : ${d.get('email')}\n\n${d.get('message')}`);}}><div className="form-row"><label>Votre nom<input name="name" autoComplete="name" required placeholder="Nom et prénom" maxLength={120}/></label><label>Votre e-mail<input name="email" autoComplete="email" type="email" required placeholder="vous@entreprise.com" maxLength={254}/></label></div><label>Vous êtes<select name="interest" defaultValue={interest||'partenaire'}><option value="partenaire">Un partenaire</option><option value="investisseur">Un investisseur</option><option value="institution">Une institution / collectivité</option><option value="étudiant ou famille">Un étudiant / une famille</option><option value="autre">Autre</option></select></label><label>Votre message<textarea name="message" required rows={4} placeholder="Parlez-nous de votre intérêt pour le projet…" maxLength={4000}/></label><p className="form-note">Le canal de réception sera activé avec les coordonnées officielles de GreenBuild. Pour l’instant, préparez votre message et copiez-le.</p><button type="submit" className="button">Préparer mon message <ArrowUpRight size={18}/></button>{prepared&&<div className="prepared-message" role="status"><p>Votre message est prêt. Il n’a pas été envoyé.</p><textarea aria-label="Message préparé à copier" readOnly value={prepared} rows={7}/><button type="button" className="text-link" onClick={async event=>{const button=event.currentTarget;try{await navigator.clipboard.writeText(prepared);button.textContent='Message copié';}catch{button.textContent='Sélectionnez le message pour le copier';}}}>Copier le message</button></div>}</form>;
}
