'use client';
import { useRef, useState } from 'react';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import { ArrowUpRight, ArrowDown, Menu, X, Leaf, Sun, Wind, GraduationCap, MapPin, Plus, Minus, ArrowRight, Globe2 } from 'lucide-react';
import CampusExperience from './campus-experience';
import { PublicSections,ContactForm } from './public-content';
import type { PublicContent } from '@/lib/types';
import { Intro, RealCampus, ConstructionScene, constructionStages } from './cinematic-scenes';
gsap.registerPlugin(ScrollTrigger, useGSAP);
const stages = constructionStages;

export default function Home({content}:{content:PublicContent}) {
const investment=content.invest[0];const contactInfo=content.contact[0];
const root = useRef<HTMLDivElement>(null); const skipIntro = useRef<() => void>(() => {}); const [introRunning,setIntroRunning]=useState(false); const [activeSection,setActiveSection]=useState(''); const [menu,setMenu]=useState(false);const [stage,setStage]=useState(0);const [faq,setFaq]=useState<number|null>(0);const [contact,setContact]=useState('');
useGSAP(()=>{
 const mm=gsap.matchMedia();
 ScrollTrigger.create({start:60,onUpdate:self=>root.current?.querySelector('.header')?.classList.toggle('is-scrolled',self.scroll()>60)});
 ['vision','campus','innovation','investir','carrieres','contact'].forEach(id=>ScrollTrigger.create({trigger:`#${id}`,start:'top 35%',end:'bottom 35%',onEnter:()=>setActiveSection(id),onEnterBack:()=>setActiveSection(id)}));
 gsap.to('.nav-progress',{scaleX:1,ease:'none',scrollTrigger:{start:0,end:'max',scrub:true}});
 mm.add('(prefers-reduced-motion: no-preference)',()=>{
 const lenis=new Lenis({duration:1.15,anchors:true});lenis.on('scroll',ScrollTrigger.update);const tick=(time:number)=>lenis.raf(time*1000);gsap.ticker.add(tick);
 let shown=false;try{shown=sessionStorage.getItem('greenbuild-intro-v2')==='seen';}catch{}
 const entrance=gsap.timeline({paused:true}).from('.hero-line > span',{yPercent:115,rotate:3,opacity:0,duration:1.3,stagger:.16,ease:'power4.out'}).from('.hero-detail',{opacity:0,y:25,stagger:.1,duration:.8},.5).from('.hero-photo',{scale:1.13,duration:2.4,ease:'power2.out'},0);
 const previousOverflow=document.body.style.overflow;let finished=false;let intro:gsap.core.Timeline|undefined;
 const finish=()=>{document.documentElement.removeAttribute('data-intro-pending');if(finished)return;finished=true;intro?.kill();gsap.set('.cinematic-intro',{autoAlpha:0,display:'none'});document.body.style.overflow=previousOverflow;lenis.start();setIntroRunning(false);entrance.play();try{sessionStorage.setItem('greenbuild-intro-v2','seen');}catch{}};
 if(!shown && window.scrollY<100 && !window.location.hash){
 setIntroRunning(true);lenis.stop();document.body.style.overflow='hidden';gsap.set('.cinematic-intro',{display:'flex',autoAlpha:1});document.documentElement.removeAttribute('data-intro-pending');
 intro=gsap.timeline({onComplete:finish});
 intro.from('.intro-blueprint>div',{scaleY:0,transformOrigin:'bottom',duration:.9,stagger:.13,ease:'power3.out'},0)
 .from('.intro-wordmark>span',{yPercent:110,opacity:0,rotateX:-70,duration:1,stagger:.15,ease:'power3.out'},.3)
 .from('.intro-overline',{opacity:0,y:10,duration:.5},.6)
 .fromTo('.intro-story>span',{y:20,opacity:0},{y:0,opacity:1,duration:.6,stagger:.55},.9)
 .fromTo('.intro-panel',{yPercent:110,rotateY:25},{yPercent:0,rotateY:0,duration:1.5,stagger:.09,ease:'power3.inOut'},1.65)
 .to('.intro-blueprint',{opacity:0,duration:.5},1.9)
 .to('.intro-copy',{y:-20,duration:1.2},2)
 .to('.intro-progress',{scaleX:1,duration:3.9,ease:'none'},0)
 .to('.cinematic-intro',{clipPath:'inset(0 0 100% 0)',duration:1.1,ease:'power4.inOut'},3.5);
 } else finish();
 skipIntro.current=finish;
 const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')finish();};window.addEventListener('keydown',escape);
 gsap.to('.hero-photo',{yPercent:18,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
 gsap.to('.hero-copy',{yPercent:-15,opacity:.15,ease:'none',scrollTrigger:{trigger:'.hero',start:'30% top',end:'bottom top',scrub:1}});
 gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:45,opacity:0,duration:.85,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));
 gsap.utils.toArray<HTMLElement>('.experience-card').forEach((el,i)=>gsap.fromTo(el,{y:32,opacity:0},{y:0,opacity:1,duration:.75,delay:i*.12,ease:'power2.out',scrollTrigger:{trigger:'.campus-experience',start:'top 72%',once:true}}));
 gsap.utils.toArray<HTMLElement>('.innovation-photo').forEach(el=>gsap.fromTo(el,{scale:1.1},{scale:1,duration:1.25,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 80%',once:true}}));
 gsap.utils.toArray<SVGElement>('.africa-map').forEach(el=>{
   gsap.fromTo(el.querySelector('.africa-map-land'),{y:20,opacity:0},{y:0,opacity:1,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 76%',once:true}});
   gsap.fromTo(el.querySelector('.map-marker-pulse'),{scale:.4,opacity:0},{scale:1,opacity:.8,duration:.9,delay:.45,ease:'back.out(2)',scrollTrigger:{trigger:el,start:'top 76%',once:true}});
   gsap.fromTo(el.querySelectorAll('.map-route'),{strokeDashoffset:600},{strokeDashoffset:0,duration:1.5,stagger:.22,ease:'power2.inOut',scrollTrigger:{trigger:el,start:'top 76%',once:true}});
   gsap.fromTo(el.querySelectorAll('.map-future'),{scale:0,opacity:0},{scale:1,opacity:1,duration:.45,stagger:.16,delay:.9,ease:'back.out(2)',scrollTrigger:{trigger:el,start:'top 76%',once:true}});
 });
 gsap.set('.construction-frame:not(.frame-0)',{clipPath:'inset(100% 0 0 0)'});
 const tl=gsap.timeline({scrollTrigger:{trigger:'.build-section',start:'top top',end:()=>`+=${window.innerHeight*4.5}`,pin:'.build-pin',scrub:.65,invalidateOnRefresh:true,onUpdate:self=>setStage(Math.min(3,Math.floor(self.progress*4)))}});
 tl.to('.build-progress',{scaleX:1,ease:'none',duration:4},0).fromTo('.construction-film',{scale:1.07},{scale:1,duration:4,ease:'none'},0);
 [1,2,3].forEach(i=>{
 tl.to(`.frame-${i}`,{clipPath:'inset(0% 0 0 0)',duration:.65,ease:'power1.inOut'},i-.15)
 .fromTo(`.frame-${i} img`,{scale:1.055},{scale:1,duration:1.1,ease:'power1.out',immediateRender:false},i-.15)
 .fromTo('.construction-scan',{top:'100%',opacity:0},{top:'0%',opacity:.8,duration:.65,ease:'power1.inOut',immediateRender:false},i-.15)
 .to('.construction-scan',{opacity:0,duration:.12},i+.5);
 });

 return ()=>{intro?.kill();entrance.kill();document.documentElement.removeAttribute('data-intro-pending');document.body.style.overflow=previousOverflow;window.removeEventListener('keydown',escape);gsap.ticker.remove(tick);lenis.destroy();skipIntro.current=()=>{};};
 });
 mm.add('(prefers-reduced-motion: reduce)',()=>{setStage(3);setIntroRunning(false);});
 return ()=>mm.revert();
},{scope:root});
const close=()=>setMenu(false);
return <div ref={root}>
<Intro active={introRunning} onSkip={()=>skipIntro.current()}/><a href="#main" className="skip-link" inert={introRunning}>Aller au contenu</a>
<header className="header" inert={introRunning}><a href="#main" className="nav-brand" aria-label="GreenBuild, accueil"><img className="nav-logo" src="/images/greenbuild-logo.png" width="116" height="74" alt="GreenBuild"/><span className="nav-tagline">DES CAMPUS. UN AVENIR.</span></a><nav id="mobile-nav" className={menu?'nav open':'nav'} aria-label="Navigation principale">{[['vision','01','La vision'],['campus','02','Le campus'],['innovation','03','La matière'],['investir','04','Investir'],['carrieres','05','Rejoindre']].map(([id,num,label])=><a key={id} href={`#${id}`} className={activeSection===id?'nav-active':''} aria-current={activeSection===id?'location':undefined} onClick={close}><span className="nav-index">{num}</span>{label}</a>)}<a className="nav-contact" href="#contact" onClick={close}>Bâtissons ensemble <ArrowUpRight size={17}/></a></nav><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'Fermer le menu':'Ouvrir le menu'} aria-expanded={menu} aria-controls="mobile-nav">{menu?<X/>:<Menu/>}</button><div className="nav-progress"/></header>
<main id="main" inert={introRunning}><section className="hero"><RealCampus className="hero-photo" priority/><div className="hero-vignette" aria-hidden="true"/><div className="hero-film-grain" aria-hidden="true"/><div className="hero-copy"><p className="eyebrow hero-detail"><span className="status-dot"/> L’AVENIR PREND RACINE ICI</p><h1><span className="hero-line"><span>Bâtir durablement,</span></span><span className="hero-line"><span>loger <em>dignement.</em></span></span></h1><p className="hero-description hero-detail">Une nouvelle génération de campus étudiants.<br/>Ancrée en Côte d’Ivoire. Tournée vers l’avenir.</p><a href="#campus" className="button hero-detail">Découvrez le projet <ArrowUpRight size={18}/></a></div><div className="hero-bottom hero-detail"><a href="#construction"><span className="scroll-orbit"><ArrowDown size={17}/></span> SCROLL POUR EXPLORER</a><p>TERRE LOCALE.<br/><strong>AMBITION AFRICAINE.</strong></p><span className="hero-location"><MapPin size={15}/> MAN, CÔTE D’IVOIRE</span></div><div className="art-caption">Vision architecturale · image de synthèse non contractuelle</div></section>
<section id="vision" className="vision section"><div className="section-kicker reveal"><span>01 / NOTRE CONVICTION</span><span>UN PROJET À IMPACT</span></div><div className="vision-grid"><h2 className="reveal">L’avenir de l’Afrique<br/>se construit aussi<br/>dans <em>ses campus.</em></h2><div className="vision-copy reveal"><p className="large-copy">Un logement digne ouvre la voie à de grandes ambitions.</p><p>GreenBuild développe des résidences universitaires écologiques pour répondre à deux enjeux essentiels : le logement étudiant et la transition écologique du bâtiment.</p><p>Des matériaux locaux, une architecture bioclimatique et des espaces de vie partagés. Une autre manière de bâtir, au service de l’éducation.</p><a href="#construction" className="text-link">De la terre au campus <ArrowDown size={17}/></a></div></div><div className="values reveal"><span><Leaf/> Construction durable</span><span><GraduationCap/> Inclusion & éducation</span><span><Sun/> Modernité africaine</span></div></section>
<section id="construction" className="build-section"><div className="build-pin"><ConstructionScene/><div className="build-top"><span className="eyebrow">02 / DE LA TERRE À L’AVENIR</span><span className="build-counter">0{stage+1} <span>/ 04</span></span></div><div className="build-editorial"><div className="build-copy"><p className="eyebrow">{stages[stage].detail}</p><h2 key={stage}>{stages[stage].title}</h2><p>{stages[stage].text}</p><span className="build-hint">Faites défiler. Le campus prend forme. <ArrowDown size={15}/></span></div><span className="build-location"><MapPin size={13}/> MAN, CÔTE D’IVOIRE</span></div><p className="build-disclaimer" role="note"><strong>Maquette exploratoire · Non officielle</strong><span>Visuels conçus pour l’élaboration du projet. Aucun aménagement définitif à ce stade.</span></p><ol className="build-stages">{stages.map(({name},i)=><li key={name} className={stage===i?'active':stage>i?'complete':''}><span>0{i+1}</span>{name}<i/></li>)}</ol><div className="build-progress"/></div></section>
<section id="campus" className="campus section"><div className="section-kicker reveal"><span>03 / LE PROJET PILOTE</span><span><MapPin size={14}/> MAN, CÔTE D’IVOIRE</span></div><div className="campus-heading reveal"><h2>Un campus pour vivre.<br/><em>Un tremplin pour demain.</em></h2><p>À proximité d’un pôle universitaire, le projet pilote de Man réunit habitat, apprentissage et vie collective dans un même lieu.</p></div><div className="campus-panel reveal"><div className="campus-picture"><RealCampus/><span className="picture-tag">LE CAMPUS GREENBUILD · VISION DU PROJET</span></div><div className="campus-stats"><span className="eyebrow">PENSÉ POUR LA VIE ÉTUDIANTE</span><p className="big-number">≈ 310</p><p>logements meublés prévus</p><div className="stat-line"><span>Matériau central</span><strong>Briques BTC</strong></div><div className="stat-line"><span>Conception</span><strong>Bioclimatique</strong></div><div className="stat-line"><span>Implantation pilote</span><strong>Man</strong></div><a href="#contact" className="text-link">Recevoir les informations du projet <ArrowUpRight size={18}/></a><small>Projet en développement. Les caractéristiques définitives seront précisées à mesure de son avancement.</small></div></div></section>
<CampusExperience/>
<section id="innovation" className="innovation section"><div className="section-kicker reveal"><span>05 / INNOVATION BTC</span><span>LA TERRE, RÉINVENTÉE</span></div><div className="innovation-grid"><div className="innovation-visual reveal"><img className="innovation-photo" src="/images/btc-craft.webp" alt="Artisan mettant en œuvre des blocs de terre comprimée sur un chantier de campus"/><span className="innovation-visual-caption"><span>01 — MATIÈRE & SAVOIR-FAIRE</span><span>BTC · TERRE LOCALE</span></span><span className="innovation-orbit" aria-hidden="true"/><span className="innovation-stamp">TERRE<br/>VIVANTE</span></div><div className="reveal"><p className="eyebrow terracotta">BRIQUES DE TERRE CRUE STABILISÉE</p><h2>L’innovation a<br/>déjà <em>ses racines.</em></h2><p>Les BTC valorisent la terre comme matériau de construction. GreenBuild les associe à une architecture contemporaine, pensée pour le climat et les usages du campus.</p><div className="innovation-item"><Leaf/><div><h3>Valoriser les ressources locales</h3><p>Faire du territoire un point de départ de la construction.</p></div></div><div className="innovation-item"><Wind/><div><h3>Concevoir avec le climat</h3><p>Intégrer la ventilation et le confort dans la réflexion architecturale.</p></div></div><div className="innovation-item"><Sun/><div><h3>Construire une vision durable</h3><p>Relier choix des matériaux, qualité d’usage et impact social.</p></div></div></div></div></section>
<section className="impact section"><div className="section-kicker reveal"><span>06 / UNE AMBITION AFRICAINE</span><span>ANCRAGE LOCAL, HORIZON CONTINENTAL</span></div><div className="impact-grid"><div className="reveal"><h2>Commencer à Man.<br/><em>Voir plus loin.</em></h2><p>Notre ambition : devenir une référence africaine du logement étudiant durable et accessible. Le pilote ivoirien constitue la première étape de cette vision.</p><div className="impact-chips"><span>Éducation</span><span>Habitat digne</span><span>Économie locale</span></div></div><div className="africa-map reveal"><div className="map-heading"><span><Globe2 size={15}/> PROJECTION CONTINENTALE</span><span>01 / 54 PAYS</span></div><div className="map-viewport"><svg viewBox="0 0 420 390" role="img" aria-label="Carte géographique de l’Afrique et de ses pays, avec le projet pilote à Man en Côte d’Ivoire"><image className="africa-map-land" href="/images/africa-countries.svg" x="0" y="0" width="420" height="390"/><g className="map-route-layer"><path className="map-route" d="M188 216 Q230 173 248 102"/><path className="map-route" d="M188 216 Q247 175 292 169"/><path className="map-route" d="M188 216 Q226 260 245 325"/><path className="map-route" d="M188 216 Q115 201 93 173"/></g><g className="map-future-points"><circle className="map-future" cx="248" cy="102" r="4"/><circle className="map-future" cx="292" cy="169" r="4"/><circle className="map-future" cx="245" cy="325" r="4"/><circle className="map-future" cx="93" cy="173" r="4"/></g><g className="map-city"><circle className="map-marker-pulse" cx="188" cy="216" r="18"/><circle cx="188" cy="216" r="5"/><path d="M193 211 225 183h65"/><rect x="255" y="160" width="110" height="36" rx="2"/><text x="263" y="175">MAN · PILOTE</text><text x="263" y="188">CÔTE D’IVOIRE</text></g></svg></div><p>Un premier campus. Une ambition africaine.</p><span className="map-concept">PERSPECTIVE DE DÉVELOPPEMENT · NON OFFICIELLE</span></div></div></section>
<section id="investir" className="invest section"><div className="invest-orbit" aria-hidden="true"/><p className="eyebrow reveal">{investment?.subtitle||'CONSTRUISONS LA SUITE ENSEMBLE'}</p><h2 className="reveal">{investment?.title||'Investir dans un campus. Croire en une génération.'}</h2><p className="reveal">{investment?.body}</p><a href={investment?.link||'#contact'} onClick={()=>setContact('investisseur')} className="button light reveal">Devenir partenaire <ArrowUpRight size={18}/></a><div className="invest-bottom reveal"><span>IMPACT SOCIAL</span><span>CONSTRUCTION DURABLE</span><span>VISION À LONG TERME</span></div></section>
<PublicSections content={content}/><section className="faq section"><div className="faq-grid"><div className="reveal"><p className="eyebrow">LES QUESTIONS ESSENTIELLES</p><h2>Comprendre<br/><em>le projet.</em></h2></div><div className="reveal">{[['À qui s’adressent les résidences GreenBuild ?','Le projet est pensé pour les étudiants et leurs familles, avec l’ambition de proposer un logement digne et un environnement favorable à la réussite académique.'],['Où se situe le projet pilote ?','Le projet pilote est prévu à Man, en Côte d’Ivoire, à proximité immédiate d’un pôle universitaire. Les informations sur le site définitif seront communiquées au fil du développement.'],['Le campus est-il déjà ouvert ?','Le campus est un projet en développement. Les dates d’ouverture, tarifs et modalités de réservation seront communiqués lorsqu’ils seront confirmés.'],['Comment participer au projet ?','Utilisez le formulaire ci-dessous pour envoyer votre demande en tant qu’investisseur, partenaire institutionnel, étudiant ou famille.']].map(([q,a],i)=><div className="faq-item" key={q}><h3><button aria-expanded={faq===i} aria-controls={`answer-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={18}/>:<Plus size={18}/>}</button></h3><div id={`answer-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></div></section>
<section id="contact" className="contact section"><div className="section-kicker reveal"><span>08 / PRENONS CONTACT</span><span>L’AVENIR COMMENCE PAR UN ÉCHANGE</span></div><div className="contact-grid"><div className="reveal"><h2>{contactInfo?.title||'Votre prochaine idée peut tout construire.'}</h2><p>{contactInfo?.subtitle}</p><div className="contact-details">{contactInfo?.email&&<a href={`mailto:${contactInfo.email}`}>{contactInfo.email}</a>}{contactInfo?.phone&&<a href={`tel:${contactInfo.phone.replace(/[^+0-9]/g,'')}`}>{contactInfo.phone}</a>}{contactInfo?.location&&<span>{contactInfo.location}</span>}{contactInfo?.body&&<p>{contactInfo.body}</p>}</div><img src="/images/greenbuild-logo.jpg" width="300" height="212" alt="GreenBuild — Bâtir durablement, loger dignement." className="contact-logo"/></div><ContactForm key={contact} interest={contact}/></div></section>
</main><footer className="footer" inert={introRunning}><div className="footer-main"><div className="footer-brand-block"><a className="footer-brand" href="#main" aria-label="GreenBuild, retour à l’accueil"><img src="/images/greenbuild-logo.png" width="120" height="77" alt="GreenBuild"/></a><p>Bâtir durablement.<br/>Loger dignement.</p><span className="footer-location"><MapPin size={14}/> MAN · CÔTE D’IVOIRE</span></div><div className="footer-column"><span className="footer-label">LE PROJET</span><a href="#vision">Notre conviction <ArrowRight size={13}/></a><a href="#campus">Le campus de Man <ArrowRight size={13}/></a><a href="#innovation">L’innovation BTC <ArrowRight size={13}/></a><a href="#investir">Investir & s’engager <ArrowRight size={13}/></a></div><div className="footer-column"><span className="footer-label">NOUS REJOINDRE</span>{content.news.length>0&&<a href="#actualites">Actualités <ArrowRight size={13}/></a>}{content.team.length>0&&<a href="#equipe">L’équipe <ArrowRight size={13}/></a>}<a href="#carrieres">Offres & candidatures <ArrowRight size={13}/></a><a href="#contact">Nous contacter <ArrowRight size={13}/></a></div><div className="footer-cta"><span className="footer-label">UNE IDÉE POUR LA SUITE ?</span><p>Les grands projets<br/>commencent par une rencontre.</p><a className="footer-contact-link" href="#contact">Parlons du projet <ArrowUpRight size={17}/></a><a className="back-top" href="#main">Retour en haut ↑</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} GreenBuild SAS</span><span>Man · Côte d’Ivoire · Afrique</span><span>Projet en développement · Visuels d’intention</span></div></footer></div>;
}
