'use client';
import { useState,type FormEvent } from 'react';
import { ArrowUpRight,MapPin,Briefcase,CheckCircle } from 'lucide-react';
import type { PublicContent,ContentRecord } from '@/lib/types';
import Modal from './modal';
export function PublicSections({content}:{content:PublicContent}){
 const [article,setArticle]=useState<ContentRecord|null>(null);const [job,setJob]=useState<ContentRecord|null>(null);
 return <>{content.news.length>0&&<section className="section editorial-section" id="actualites"><div className="section-kicker"><span>ACTUALITÉS</span><span>LE PROJET EN MOUVEMENT</span></div><h2>Les nouvelles <em>de GreenBuild.</em></h2><div className="editorial-grid">{content.news.map(item=><button className="editorial-card" onClick={()=>setArticle(item)} key={item.id}>{item.image&&<img src={item.image} alt="" loading="lazy"/>}<div><p className="eyebrow">{item.subtitle||'GREENBUILD'}</p><h3>{item.title}</h3><p>{item.body.slice(0,150)}{item.body.length>150?'…':''}</p><span className="text-link">Lire l’actualité <ArrowUpRight size={16}/></span></div></button>)}</div></section>}
 {content.team.length>0&&<section className="section team-section" id="equipe"><div className="section-kicker"><span>L’ÉQUIPE</span><span>UNE AMBITION COLLECTIVE</span></div><h2>Des personnes.<br/><em>Une même conviction.</em></h2><div className="team-grid">{content.team.map(person=><article key={person.id} className="team-card">{person.image?<img src={person.image} alt={person.title} loading="lazy"/>:<div className="team-initials" aria-hidden="true">{person.title.split(' ').map(x=>x[0]).slice(0,2).join('')}</div>}<h3>{person.title}</h3><p className="eyebrow terracotta">{person.subtitle}</p><p>{person.body}</p>{person.link&&<a href={person.link} className="text-link" target="_blank" rel="noopener noreferrer">Profil <ArrowUpRight size={16}/></a>}</article>)}</div></section>}
 <section className="section careers-section" id="carrieres"><div className="section-kicker"><span>REJOIGNEZ GREENBUILD</span><span>LES TALENTS CONSTRUISENT L’AVENIR</span></div><div className="careers-heading"><h2>Votre talent.<br/><em>Notre prochaine étape.</em></h2><p>Contribuez à un projet qui relie habitat, éducation et construction durable.</p></div>{content.jobs.length?<div className="job-list">{content.jobs.map(offer=><button key={offer.id} className="job-row" onClick={()=>setJob(offer)}><span><small>{offer.subtitle||'GREENBUILD'}</small><h3>{offer.title}</h3><span className="job-meta"><span><MapPin size={14}/>{offer.location||'À préciser'}</span><span><Briefcase size={14}/>{offer.contract||'À préciser'}</span></span></span><span className="job-cta">Voir l’offre <ArrowUpRight size={19}/></span></button>)}</div>:<div className="empty-jobs"><p>Aucun poste ouvert pour le moment.</p><span>Les prochaines opportunités seront publiées ici.</span></div>}</section>
 {article&&<Modal title={article.title} onClose={()=>setArticle(null)}>{article.image&&<img className="article-cover" src={article.image} alt=""/>}<div className="modal-editorial"><p className="eyebrow terracotta">{article.subtitle||'ACTUALITÉ GREENBUILD'}</p><h2>{article.title}</h2><div className="rich-text">{article.body}</div>{article.link&&<a href={article.link} target="_blank" rel="noopener noreferrer" className="text-link">En savoir plus <ArrowUpRight size={16}/></a>}</div></Modal>}
 {job&&<Modal title={job.title} onClose={()=>setJob(null)}><div className="modal-editorial"><p className="eyebrow terracotta">REJOINDRE GREENBUILD</p><h2>{job.title}</h2><p className="job-meta"><span>{job.location}</span><span>{job.contract}</span></p><div className="rich-text">{job.body}</div><ApplicationForm job={job}/></div></Modal>}</>;
}
function ApplicationForm({job}:{job:ContentRecord}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);data.set('jobId',job.id);try{const response=await fetch('/api/applications',{method:'POST',body:data});const result=await response.json();if(!response.ok)throw new Error(result.error);setSuccess(result.message);}catch(error){setError(error instanceof Error?error.message:'Impossible d’envoyer la candidature.');}finally{setBusy(false);}}
 if(success)return <div className="form-success" role="status"><CheckCircle/><h3>Candidature reçue.</h3><p>{success}</p></div>;
 return <form className="application-form" onSubmit={submit}><h3>Présentez-nous votre candidature.</h3><div className="form-row"><label>Nom et prénom<input name="name" required maxLength={120} autoComplete="name"/></label><label>E-mail<input name="email" required type="email" maxLength={254} autoComplete="email"/></label></div><label>Téléphone<input name="phone" type="tel" maxLength={80} autoComplete="tel"/></label><label>Votre motivation<textarea name="message" rows={5} required maxLength={5000}/></label><label>Votre CV · PDF, 5 Mo maximum<input name="cv" type="file" accept=".pdf,application/pdf" required onChange={event=>{const file=event.target.files?.[0];event.target.setCustomValidity(file&&file.size>5*1024*1024?'Le CV doit faire moins de 5 Mo.':'');}}/></label><label className="honey" aria-hidden="true">Site web<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="consent"><input type="checkbox" name="consent" required/>J’accepte que GreenBuild utilise ces informations et mon CV pour étudier ma candidature. Ils seront accessibles à l’équipe administratrice du site.</label>{error&&<p role="alert" className="form-error">{error}</p>}<button type="submit" className="button" disabled={busy}>{busy?'Envoi en cours…':'Envoyer ma candidature'}<ArrowUpRight size={17}/></button></form>;
}
export function ContactForm({interest}:{interest:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(form.entries()),consent:form.get('consent')==='on'})});const result=await response.json();if(!response.ok)throw new Error(result.error);setSuccess(result.message);}catch(error){setError(error instanceof Error?error.message:'Impossible d’envoyer votre message.');}finally{setBusy(false);}}
 if(success)return <div className="form-success" role="status"><CheckCircle/><h3>Merci pour votre message.</h3><p>{success}</p></div>;
 return <form className="contact-form" onSubmit={submit}><div className="form-row"><label>Votre nom<input name="name" autoComplete="name" required placeholder="Nom et prénom" maxLength={120}/></label><label>Votre e-mail<input name="email" autoComplete="email" type="email" required placeholder="vous@entreprise.com" maxLength={254}/></label></div><label>Vous êtes<select name="interest" defaultValue={interest||'partenaire'}><option value="partenaire">Un partenaire</option><option value="investisseur">Un investisseur</option><option value="institution">Une institution / collectivité</option><option value="étudiant ou famille">Un étudiant / une famille</option><option value="autre">Autre</option></select></label><label>Votre message<textarea name="message" required rows={4} placeholder="Parlez-nous de votre intérêt pour le projet…" maxLength={5000}/></label><label className="honey" aria-hidden="true">Site web<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="consent"><input type="checkbox" name="consent" required/>J’accepte que GreenBuild utilise mes coordonnées pour traiter ma demande.</label>{error&&<p role="alert" className="form-error">{error}</p>}<button type="submit" className="button" disabled={busy}>{busy?'Envoi en cours…':'Envoyer mon message'}<ArrowUpRight size={18}/></button></form>;
}
